<a href="https://colab.research.google.com/github/princeiiitk/CampusX-ML/blob/main/OneHotEncoding/OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone 'https://github.com/princeiiitk/CampusX-ML'

Cloning into 'CampusX-ML'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 17 (delta 1), reused 9 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (17/17), 53.79 KiB | 4.89 MiB/s, done.
Resolving deltas: 100% (1/1), done.

In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('/content/CampusX-ML/OneHotEncoding/cars.csv')

In [5]:
df.head(11)

      brand  km_driven    fuel         owner  selling_price
0    Maruti     145500  Diesel   First Owner         450000
1     Skoda     120000  Diesel  Second Owner         370000
2     Honda     140000  Petrol   Third Owner         158000
3   Hyundai     127000  Diesel   First Owner         225000
4    Maruti     120000  Petrol   First Owner         130000
5   Hyundai      45000  Petrol   First Owner         440000
6    Maruti     175000     LPG   First Owner          96000
7    Maruti       5000  Petrol  Second Owner          45000
8    Toyota      90000  Diesel   First Owner         350000
9      Ford     169000  Diesel   First Owner         200000
10  Renault      68000  Diesel  Second Owner         500000

In [6]:
df.columns

Index(['brand', 'km_driven', 'fuel', 'owner', 'selling_price'], dtype='object')

In [8]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [12]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

# OneHotEncoding using pandas

In [11]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [10]:
df.columns

Index(['brand', 'km_driven', 'fuel', 'owner', 'selling_price'], dtype='object')


# 3. OneHotEncoding using Sklearn

In [15]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [16]:
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [28]:
ohe = OneHotEncoder(drop='first',dtype=np.int32)

In [25]:
X_train_new=ohe.fit_transform(X_train[['fuel','owner']])

In [26]:
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [30]:
print(X_train[['brand','km_driven']].values.shape)
print(X_train_new.shape)

(6502, 2)
(6502, 7)

In [23]:
X_train_new.shape

(6502, 7)